### ISSUE TITLE
Missing versions: 0.7.2 & 0.7.3

### ISSUE THREAD

**Issue by FDuros** [theganyo/swagger-node-runner#104]
Hi,

On the npm repository, the last version of swagger-node-runner is [0.7.3](https://www.npmjs.com/package/swagger-node-runner). However, the git last version is 0.7.1

What are the changes?

Thanks!

**Comment by theganyo** [comment]
Sorry that the release notes are not up to date. There were a couple of patches. See:
https://github.com/theganyo/swagger-node-runner/commits/master
