### ISSUE TITLE
Connect Middleware ignores res.status set in controller when using res.json

### ISSUE THREAD

**Issue by schlundd** [theganyo/swagger-node-runner#2]
The HTTP status code in res.json is set always set to 200. It should be possible to set a different code within the controller, though. Removing line 220 in connect_middleware.js (res.statusCode = 200) solves the issue without having any negative effect (as far as I see).

So... am I missing a sideeffect/wanted behavior or should the line be removed?

Cheers.

**Comment by theganyo** [comment]
How about we set it only if you haven't already?

**Comment by schlundd** [comment]
Makes sense. Cheers.

**Comment by saul-mtz** [comment]
Hi, I'm currently using the v4.4 but this fix is not there, are you planning to included it in next releases?

**Comment by theganyo** [comment]
Yes. This will be included in a new release soon.
