### ISSUE TITLE
Latest NPM breaks swagger-node-runner CORS

### ISSUE THREAD

**Issue by NitroPye** [theganyo/swagger-node-runner#23]
All modules are in a flat format now and it appears that having swagger-node-runner/fittings/cors.js and the module cors (in the new flat format) breaks what is loaded via require.

I can test this theory by installing a sample project with the latest npm (3.3.12) and seeing it break then going into the swagger-node-runner module and renaming the cors wrapper (and relevant config for bagpipes) and it works.

Not sure of an elegant workaround for this. Renaming fittings/cors.js would cause problems with existing projects.

**Comment by NitroPye** [comment]
Not sure if this is a good solution. It will require people to update their projects configs.

https://github.com/theganyo/swagger-node-runner/pull/24

**Comment by theganyo** [comment]
Thanks. This is a known issue that was addressed a while back by removing "node_modules" from the "fittingsDirs" array in the config. Where are you still seeing this setting?

**Comment by NitroPye** [comment]
Ah good catch and thanks for the fast response. It was still in my swagger config file (default.yaml) since I started the project quite some time ago.
