### ISSUE TITLE
500 error instead of 405 on non allowed method

### ISSUE THREAD

**Issue by cgalibern** [theganyo/swagger-node-runner#29]
When request to non allowed method in swagger.yaml I get a 500 instead of 405:

```
error: Sending 500 ("Server Error") response: 
 Error: Path [aPathApi] defined in Swagger, but GET operation is not.
    at middleware (/projectdir/node_modules/swagger-sails-hook/node_modules/swagger-node-runner/lib/connect_middleware.js:31:21)
...
at callbacks  (/projectdir/node_modules/sails/node_modules/express/lib/router/index.js:167:11) { [Error: Path [aPathApi] defined in Swagger, but GET operation is not.] statusCode: 405, allowedMethods: [ 'DELETE', 'POST' ] }
```
Is there an option to overide this ?

https://github.com/theganyo/swagger-node-runner/blob/master/lib/connect_middleware.js#L40

Thanks

**Comment by cgalibern** [comment]
@theganyo 

Since the status is known 403,  instead of

```javascript
return next(err);
```

Should it stop here and send response ?

```javascript
return (res.json(err.statusCode,err));
```

**Comment by theganyo** [comment]
Hmm. Yes, you should get a 405. Sounds like a bug somewhere.

But, no, I don't believe it should immediately return nor send json. That makes too many assumptions regarding flow and output format.

**Comment by theganyo** [comment]
Fix released. https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.16.
