### ISSUE TITLE
Route parameters aren't available in Hapi

### ISSUE THREAD

**Issue by vitorbaptista** [theganyo/swagger-node-runner#33]
I'm using `swagger-node-runner` through `swagger-hapi`. The related dependencies are:

> ├─┬ swagger-hapi@0.6.0
> │ └─┬ swagger-node-runner@0.6.16 
> │   └─┬ sway@0.6.0 
> │     └── glob@5.0.15 

When handling a request with a parameter in the path, the `request.swagger.params` object is undefined. I looked around `request` and `request.swagger` thinking it could've been renamed, but couldn't find the parameter anywhere.

Downgrading `swagger-hapi` to `0.1.0`, which in turn downgrades `swagger-node-runner` to `0.5.13` fixes the issue.

If it helps, the handler I'm running is at https://github.com/opentrials/api/blob/master/api/controllers/trials.js#L4.

**Comment by marcofranssen** [comment]
Same for express/connect middleware

**Comment by theganyo** [comment]
Hey Guys,

I'm not sure if this is your issue, but if you haven't, please be sure you follow the instructions under "upgrading" here: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.0.

Please let me know if that solves the problem.
Scott
