### ISSUE TITLE
Why I have to access params through req.swagger.params

### ISSUE THREAD

**Issue by osukaa** [theganyo/swagger-node-runner#35]
Hi,

Just as the question says. Is there a way that in express this could be like it normally works `req.params` in some type of config?

Cross-ref https://github.com/apigee-127/swagger-express/issues/9

**Comment by theganyo** [comment]
There's a mismatch considering req.params in express don't have validation. What would happen for parameters that aren't valid?

**Comment by osukaa** [comment]
Parameters should be validated by a middleware before it goes into the endpoint handler. Which is what swagger-node is doing but it's not populating the standard `req.params`.

**Comment by theganyo** [comment]
Right. But some parameters might be invalid. In addition, some might be required but allowed to be null. These possibilities can't be handled by the simple req.params key/value structure that express has.
