### ISSUE TITLE
New release with latest Sway release?

### ISSUE THREAD

**Issue by rsinger** [theganyo/swagger-node-runner#38]
Sway just released 1.0.0 https://github.com/apigee-127/sway/releases/tag/v1.0.0 which introduces a bunch of improvements, would it be possible to get a new release of swagger-node-runner which includes it?

**Comment by theganyo** [comment]
Thanks for pointing that out. Unfortunately, it appears that incompatibilities were introduced with the latest version of Sway. So until the reasons for the test failures can be identified and addressed, I won't be able to release a new version based on that. Hopefully I'll be able to get to it soon, but I don't have a timeline at this point.

**Comment by rsinger** [comment]
Ok, that's understandable.  Thanks for looking into and I'll hang tight for now.

**Comment by vgoloviznin** [comment]
Is there any estimation regarding when the package will get updated sway? :)

**Comment by theganyo** [comment]
I'd love to get this done as quickly as possible, but it will require extra engineering time that I haven't been able to allot just yet. If anybody has a minute and could help out with a PR - or perhaps just by simply identifying the changes that will need to be made and posting the findings here, that would help greatly. Otherwise, I'll try to get to it "real soon".

**Comment by sherpya** [comment]
sway 0.6.0 is slow as hell and does not work for, I've forced 1.0.0 and does not exposes slow startup, try using this configuration in the same order:

```
    swagger_controllers:
      - onError: json_error_handler
      - cors
      - swagger_security
      - swagger_params_parser
      - express_compatibility
      - _swagger_validate
      - _router
```

**Comment by theganyo** [comment]
@sherpya You've been able to use Sway 1.0.0 without any code modifications?

**Comment by sherpya** [comment]
I've just created a project from scratch using `swagger-tools`, I selected `restify`,
then I bumped `swagger-restify-mw` to `0.6.0` that uses `swagger-node-runner` `0.6.16`.
Then bumped `sway` to `1.0.0` in `swagger-node-runner`.

The sample call fails with `req.query must be provided for 'query' parameters`,
it looks like the new validator expects `req.query` so `express_compatibility` should be chained before
validation, but it's not enough, I had to add also `swagger_params_parser`
Now the sample hello world works

Please note that right now `swagger-tools` and `sway` handle differently circular definitions, `swagger-tools` silently drops the schema and the validation of a definition  while `sway` makes it invalid, please refer to https://github.com/apigee-127/sway/issues/85

**Comment by theganyo** [comment]
Sway 1.0 has been implemented: https://github.com/theganyo/swagger-node-runner/releases/tag/v0.7.0
