### ISSUE TITLE
Add support for enabling Swagger UI

### ISSUE THREAD

**Issue by jadbox** [theganyo/swagger-node-runner#4]
Perhaps as a config option

**Comment by oliverhr** [comment]
Yeap I hate o add swagger-tools to load on app.js when generated with `swagger-project create`

```
var SwaggerExpress = require('swagger-express-mw');
var SwaggerUi = require('swagger-tools/middleware/swagger-ui');
var express = require('express');

module.exports ...

...

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // ----- xx ----
  app.use(SwaggerUi(swaggerExpress.runner.swagger));

  // install middleware
  swaggerExpress.register(app);
  ...
```

**Comment by oliverhr** [comment]
Note we can load directy UI:

```javascript
'use strict';

var SwaggerExpress = require('swagger-express-mw');
var app = require('express')();
module.exports = app; // for testing

var config = {
  appRoot: __dirname // required config
};

SwaggerExpress.create(config, function(err, swaggerExpress) {
  if (err) { throw err; }

  // enable SwaggerUI
  app.use(swaggerExpress.runner.swaggerTools.swaggerUi(config));

  // install middleware
  swaggerExpress.register(app);

  var port = process.env.PORT || 10010;
  app.listen(port);

  console.log('try this:\ncurl http://127.0.0.1:' + port + '/hello?name=Scott');
});
```

**Comment by tanzim** [comment]
Hi,
It seems that with the latest changes to swagger-node-runner, the workaround to get Swagger UI running (see above) no longer works as the dependency on swagger-tools has been removed completely.
Is there a workaround available?

**Comment by theganyo** [comment]
A simple workaround is to just install swagger-ui into a project directory and serve it with the [serve-static](https://www.npmjs.com/package/serve-static) middleware.

**Comment by dmk255** [comment]
@theganyo Could you explain a little more about how you implemented that?

**Comment by theganyo** [comment]
@dmk255 All you need to do it configure/customize your swagger-ui as you would normally. Then, put `swagger-ui/dist` in your application folder. Let's say we put it in folder `/ui`, then we simply serve it on whatever path, say, `/swagger-ui`. It would be something like this (not tested):
```
app.use(serveStatic('ui', {'swagger-ui': ['index.html']}))
```
