### ISSUE TITLE
No error thrown on unconfigured parameters

### ISSUE THREAD

**Issue by wjagodfrey** [theganyo/swagger-node-runner#50]
```
project
└─┬ swagger-express-mw@0.6.0
  └── swagger-node-runner@0.6.16
```

**Issue:** Passing an unconfigured parameter (not in swagger request schema) in a POST body doesn't throw a validation error.

**Detail:** Talking to the Swagger spec guys on IRC, it turns out that this "missing" behaviour isn't explicitly stated in the spec but was intended to exist, at least optionally. Does `swagger-node-runner` have this ability?

**Comment by wjagodfrey** [comment]
I'm assuming this is a sway issue. There has been no way left to pass options to sway: https://github.com/theganyo/swagger-node-runner/blob/master/index.js#L185

**Comment by theganyo** [comment]
Yes, this will have to be addressed in Sway. 

Leaving the link to the Sway issue here for posterity: https://github.com/apigee-127/sway/issues/94
