### ISSUE TITLE
Response validation missing?

### ISSUE THREAD

**Issue by chrisegner** [theganyo/swagger-node-runner#63]
It appears that swagger_validate fitting no longer supports response validation.  What's the long term plan?  Is there a recommended work around for now?  

There appears be code in the swagger-tools project's swagger-validator middleware, but it's not clear how these two should be integrated (and swagger-tools is technically deprecated).

**Comment by theganyo** [comment]
It does, but it's changed. Please check this out:
https://github.com/theganyo/swagger-node-runner/releases/tag/v0.6.4

**Comment by chrisegner** [comment]
Ah, okay.  Thanks you - that clears it up.  I missed that because I wasn't upgrading.  I'm new to swagger and trying to integrate it into an existing (sizable) project.  There are a *lot* of different packages to sort through, some of which are no longer part of the current right way, and I missed that detail.  I wish there were a guide to the distinctions among swagger-node, swagger-node-express, swagger-express-mw (aka swagger-express), swagger-tools, and so on.

Perhaps the swagger-node template could be updated (still references the old validateResponse option on the swagger_validate fixture).  It might also be helpful to migrate some of the release notes into the documentation for this project.

**Comment by theganyo** [comment]
I agree. Some documentation catch-up work needs to be done. Sorry about that!
