### ISSUE TITLE
when should we expect the next npm-published version?

### ISSUE THREAD

**Issue by osher** [theganyo/swagger-node-runner#76]
can't wait...

any timeline for that?

**Comment by theganyo** [comment]
You're the prime contributor to this next release. What's your confidence level in it as a patch release?

**Comment by osher** [comment]
Well. 
I know that about all my PRs we discussed and made sure we're backward compatible.
At least by design.
I did my best to add tests - I was stopped only on tests for `connect_middeware` - which has no unit-test suite. however, I do see it's involved in e2e tests - so...

If there are more tests you'd like to add to the test suite - let's discuss it - I'll try to be quick about it

**Comment by theganyo** [comment]
No, I don't have anything in mind. I just wanted to get your feedback. I think we can move forward with what we have now.

**Comment by theganyo** [comment]
Release notes:  https://github.com/theganyo/swagger-node-runner/releases/edit/untagged-5ed17a7cd68bc47bdda3

Please let me know of any comments / corrections.

**Comment by osher** [comment]
it won't let me open the link 😮 
is it a permissions thing?

**Comment by theganyo** [comment]
Must be permissions. Ok, I just went ahead and published it (both git & npm). Please let me know if you see any issues.
https://github.com/theganyo/swagger-node-runner/releases/tag/v0.7.1

**Comment by osher** [comment]
Scott - that's wonderful! 

Now I can decouple my handlers from `ctx.response`!

For my next trick - decouple handlers from `ctx.request`. Basically - everything is on `ctx.request.swagger.params`, so I think we can spare the user following this trail...

Anyway - I'll open a new thread for that :)

**Comment by osher** [comment]
Thanks again!! 😄

**Comment by osher** [comment]
Ah - one point missed from the release notes: 
You can now use `fitting/swagger-cors` instead `fitting/cors` of  and include your node_modules in `fittingsDirs`

**Comment by theganyo** [comment]
Thanks. Updated.

**Comment by osher** [comment]
swell. 
I just found there's another way to do it
```
  - _cors:
    name: cors
    type: user     # <--  look it only in user fittings
    ...    
```
